name: Build

on:
  create:
    tags: [v*]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 13
          registry-url: 'https://registry.npmjs.org'

      - name: Install NPM packages
        run: npm ci

      - name: Build package
        run: npm run build-ci

      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_PUBLISH_TOKEN }}
